### ISSUE TITLE
Donate Macbook

### ISSUE THREAD

**Issue by bitnom** [Senketsu/nsu#1]
What if I donate you a vmware image?

**Comment by Senketsu** [comment]
The donate macbook line was more of a joke than anything, though I would certainly be more motivated to invest my time and learn to code for Mac if I had actual machine of my own.

Last time i tried OSX inside VM, it ran like powerpoint presentation..
I don't know if that was issue of the virtualization software or the version of OSX or apple being ass or my potato performance and I didn't bother finding out.

It's just too much hassle and very likely waste of time in my opinion.
