### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by bitnom** [Senketsu/nsu#2]
This is Linux host.

Building nsu/nsu using c backend
    Prompt: Build failed for 'nsu@0.1.4', would you like to try installing 'nsu@#head' (latest unstable)? [y/N]
    Answer: n
     Error: Aborting installation due to build failure

**Comment by Senketsu** [comment]
Haven't checked out my GitHub in a while so I'm sorry for the late reply.
The issue is the x11 lib:
https://github.com/nim-lang/x11/issues/24#issuecomment-507033833

Updated the source. Should compile now.
